### PR TITLE
Change if condition value for denominators in generated code

### PR DESCRIPTION
**Pull request by Kgeorgouli**

### CODE REVIEW

**Review by JaeseungYeom — COMMENTED** [review]
Add this line 
const std::string zero = "static_cast<" + Real + ">(0)";

Then, change 0.0 to zero

**Comment by Kgeorgouli** [comment]
Done.
Thank you.
Konstantia

**Comment by JaeseungYeom** [comment]
A styling suggestion. Add a space around '<<', and then merge.

**Review by JaeseungYeom — APPROVED** [review]

**Comment by Kgeorgouli** [comment]
Done.

Thank you.
Konstantia

**Pull request merged**
